spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 607139602650-80d112noi9ulkbkdb60rf6r4u0q5knsd.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile